(() => {
  "use strict";
  const S={quotes:[],events:[],orders:[],inventory:[],expenses:[],tasks:[],staff:[],availability:{},section:"dashboard",cal:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
  const money=v=>new Intl.NumberFormat("nl-BE",{style:"currency",currency:"EUR"}).format(Number(v)||0);
  const date=v=>{if(!v)return "-";const d=new Date(String(v).length===10?v+"T00:00:00":v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("nl-BE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)};
  const dt=v=>{if(!v)return "-";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("nl-BE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
  const time=v=>v?String(v).slice(0,5):"-";
  const qStatus=s=>({new:"Nieuw",in_progress:"In behandeling",accepted:"Aanvaard",rejected:"Geweigerd",cancelled:"Geannuleerd"}[s]||s||"Onbekend");
  const payStatus=s=>({paid:"Betaald",open:"Open",pending:"In afwachting",failed:"Mislukt",canceled:"Geannuleerd",expired:"Verlopen",creation_failed:"Aanmaken mislukt"}[s]||s||"Onbekend");
  const fulfillStatus=s=>({new:"Nieuw",preparing:"In voorbereiding",ready:"Klaar",processing:"In behandeling",shipped:"Verzonden",completed:"Afgerond",cancelled:"Geannuleerd"}[s]||s||"Nieuw");
  const badge=s=>["paid","completed","accepted","confirmed","ready"].includes(s)?"badge badge-green":["rejected","cancelled","failed","canceled","expired","creation_failed","refunded"].includes(s)?"badge badge-red":["in_progress","processing","preparing","pending","open"].includes(s)?"badge badge-amber":s==="shipped"?"badge badge-cyan":"badge badge-blue";
  const orderCustomer=o=>[o.customer_first_name,o.customer_last_name].filter(Boolean).join(" ").trim()||o.customer_email||"-";
  const toast=(m,type)=>{const e=$("#toast");if(!e)return;e.textContent=m;e.className="toast show "+(type||"");clearTimeout(toast.t);toast.t=setTimeout(()=>e.className="toast",3200)};
  async function api(action,payload){
    const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},credentials:"same-origin",body:JSON.stringify(Object.assign({action},payload||{}))});
    const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Serverfout.");return d;
  }
  async function load(){
    const d=await api("bootstrap");
    S.quotes=d.quotes||[];S.events=d.events||[];S.orders=d.orders||[];S.inventory=d.inventory||[];S.expenses=d.expenses||[];S.tasks=d.tasks||[];S.staff=d.staff||[];S.availability=d.availability||{};
    render();
  }
  async function login(){
    const pin=$("#loginPin").value.trim(), email=$("#loginEmail").value.trim(), pass=$("#loginPassword").value;
    $("#loginError").textContent="";
    $("#loginButton").disabled=true;$("#loginButton").textContent="Controleren…";
    try{const d=await api("login",{pin,email,password:pass});showApp(d.session);await load()}catch(e){$("#loginError").textContent=e.message}finally{$("#loginButton").disabled=false;$("#loginButton").textContent="Dashboard openen"}
  }
  function showApp(session){
    $("#loginScreen").style.display="none";$("#app").classList.add("ready");$("#currentUser").textContent=session?.name||"Hummie Bear";$("#currentRole").textContent=session?.role||"owner";
  }
  async function start(){
    try{const r=await fetch("/api/admin",{credentials:"same-origin"});if(r.ok){const d=await r.json();showApp(d.session);await load();return}}catch{}
    $("#loginScreen").style.display="grid";
  }
  async function logout(){try{await api("logout")}catch{}location.reload()}
  function metrics(){
    const paid=S.orders.filter(o=>o.payment_status==="paid"), webshop=paid.reduce((a,o)=>a+Number(o.total||0),0);
    const eventRev=S.events.filter(e=>e.status==="confirmed").reduce((a,e)=>a+Number(e.final_price||0),0);
    const openQuotes=S.quotes.filter(q=>["new","in_progress"].includes(q.status)).length;
    const process=paid.filter(o=>!["completed","cancelled"].includes(o.status)).length;
    const upcoming=S.events.filter(e=>e.status==="confirmed"&&new Date((e.event_date||"")+"T23:59:59")>=new Date()).length;
    const accepted=S.quotes.filter(q=>q.status==="accepted").length;
    return{webshop,eventRev,total:webshop+eventRev,openQuotes,process,upcoming,orders:S.orders.length,conversion:S.quotes.length?100*accepted/S.quotes.length:0};
  }
  function title(section){
    const m={dashboard:["Overzicht","Live operationeel overzicht van Hummie Bear."],quotes:["Aanvragen","Leads, offertes en opvolging."],orders:["Bestellingen","Webshoporders, betalingen en verwerking."],events:["Evenementen","Alle bevestigde events en praktische details."],calendar:["Kalender","Planning en bezetting."],customers:["Klanten","Gecombineerd overzicht van klanten en activiteit."],products:["Producten & voorraad","Verkoopprestaties en voorraad."],finance:["Financieel","Omzet, events, kosten en betaalstatus."],staff:["Medewerkers","Accounts, rollen en toegang."],tasks:["Taken","Operationele opvolging voor jou en je team."],reports:["Rapporten","Exports en managementoverzicht."],settings:["Instellingen","Koppelingen, systeemstatus en veiligheid."]}[section]||["Hummie Bear","Beheeromgeving"];$("#pageTitle").textContent=title(section)[0];$("#pageSubtitle").textContent=title(section)[1];$("#breadcrumbCurrent").textContent=title(section)[0]}
  function section(s){S.section=s;$$(".section").forEach(x=>x.classList.toggle("active",x.id==="section-"+s));$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.section===s));title(s);render()}
  function render(){
    if(S.section==="dashboard")renderDashboard();else if(S.section==="quotes")renderQuotes();else if(S.section==="orders")renderOrders();else if(S.section==="events")renderEvents();else if(S.section==="calendar")renderCalendar();else if(S.section==="customers")renderCustomers();else if(S.section==="products")renderProducts();else if(S.section==="finance")renderFinance();else if(S.section==="staff")renderStaff();else if(S.section==="tasks")renderTasks();else if(S.section==="reports")renderReports();else if(S.section==="settings")renderSettings();
  }
  function renderDashboard(){
    const m=metrics();$("#kpiRevenue").textContent=money(m.total);$("#kpiOrders").textContent=m.orders;$("#kpiQuotes").textContent=m.openQuotes;$("#kpiEvents").textContent=m.upcoming;$("#kpiProcess").textContent=m.process;$("#kpiConversion").textContent=m.conversion.toFixed(0)+"%";
    const recent=S.orders.slice(0,6);$("#recentOrders").innerHTML=recent.length?recent.map(o=>'<div class="list-item"><div class="list-main"><strong>'+esc(o.order_number||o.id)+'</strong><span>'+esc(orderCustomer(o))+' · '+dt(o.created_at)+'</span></div><div><span class="'+badge(o.payment_status)+'">'+esc(payStatus(o.payment_status))+'</span><div class="money" style="font-size:12px;margin-top:4px;text-align:right">'+money(o.total)+'</div></div></div>').join(""):'<div class="empty"><strong>Geen bestellingen</strong>Nieuwe orders verschijnen hier automatisch.</div>';
    const upcoming=S.events.filter(e=>e.status==="confirmed"&&new Date((e.event_date||"")+"T23:59:59")>=new Date()).sort((a,b)=>String(a.event_date).localeCompare(String(b.event_date))).slice(0,6);
    $("#upcomingEvents").innerHTML=upcoming.length?upcoming.map(e=>'<div class="list-item"><div class="list-main"><strong>'+esc(e.event_name||e.title||"Event")+'</strong><span>'+date(e.event_date)+' · '+time(e.start_time)+'–'+time(e.end_time)+' · '+esc(e.location||"-")+'</span></div><span class="badge badge-blue">'+esc(e.edition||"Event")+'</span></div>').join(""):'<div class="empty"><strong>Geen komende events</strong></div>';
    const low=S.inventory.filter(x=>Number(x.stock_quantity)<=Number(x.min_stock));
    $("#dashboardAlerts").innerHTML=low.length?low.slice(0,5).map(x=>'<div class="list-item"><div class="list-main"><strong>'+esc(x.name)+'</strong><span>'+Number(x.stock_quantity)+' '+esc(x.unit||"stuks")+' · minimum '+Number(x.min_stock)+'</span></div><span class="badge badge-red">Lage voorraad</span></div>').join(""):'<div class="empty"><strong>Geen kritieke meldingen</strong>Operationeel ziet alles er rustig uit.</div>';
    if(window.Chart){const labels=[];const data=[];for(let i=29;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const iso=d.toISOString().slice(0,10);labels.push(iso.slice(5));data.push(S.orders.filter(o=>o.payment_status==="paid"&&String(o.paid_at||o.created_at||"").slice(0,10)===iso).reduce((a,o)=>a+Number(o.total||0),0))};if(S.revChart)S.revChart.destroy();S.revChart=new Chart($("#revenueChart"),{type:"line",data:{labels,datasets:[{label:"Omzet",data,borderColor:"#4f46e5",backgroundColor:"rgba(79,70,229,.08)",fill:true,tension:.35,pointRadius:1.5,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>"€"+v}},x:{grid:{display:false}}}}})}
  }
  function renderQuotes(){
    const search=($("#quoteSearch")?.value||"").toLowerCase(),status=$("#quoteStatus")?.value||"all",edition=$("#quoteEdition")?.value||"all";
    const a=S.quotes.filter(q=>{const t=[q.name,q.organisation,q.email,q.phone,q.event_name,q.location,q.edition].filter(Boolean).join(" ").toLowerCase();return(!search||t.includes(search))&&(status==="all"||q.status===status)&&(edition==="all"||q.edition===edition)}).sort((x,y)=>String(y.created_at).localeCompare(String(x.created_at)));
    $("#quotesBody").innerHTML=a.length?a.map(q=>'<tr><td><div class="strong">'+esc(q.name||"-")+'</div><div class="muted">'+esc(q.email||"")+'</div></td><td><div class="strong">'+esc(q.event_name||"-")+'</div><div class="muted">'+date(q.event_date)+' · '+time(q.start_time)+'–'+time(q.end_time)+'</div></td><td>'+esc(q.location||"-")+'<div class="muted">'+esc(q.guests||"-")+' gasten</div></td><td><span class="'+badge(q.status)+'">'+esc(qStatus(q.status))+'</span><div style="margin-top:4px"><span class="badge badge-blue">'+esc(q.edition||"-")+'</span></div></td><td class="money">'+money(q.final_price??q.estimated_price)+'</td><td><div class="table-actions"><button class="mini-btn" data-act="qdetail" data-id="'+esc(q.id)+'">Details</button><button class="mini-btn primary" data-act="qedit" data-id="'+esc(q.id)+'">Bewerken</button>'+(q.status!=="accepted"?'<button class="mini-btn" data-act="qaccept" data-id="'+esc(q.id)+'">Aanvaarden</button>':"")+'</div></td></tr>').join(""):'<tr><td colspan="6"><div class="empty"><strong>Geen aanvragen</strong>Pas de filters aan.</div></td></tr>';
  }
  function renderOrders(){
    const search=($("#orderSearch")?.value||"").toLowerCase(),p=$("#orderPayment")?.value||"all",f=$("#orderFulfillment")?.value||"all";
    const a=S.orders.filter(o=>{const t=[o.order_number,orderCustomer(o),o.customer_email,o.shipping_street,o.shipping_city].filter(Boolean).join(" ").toLowerCase();return(!search||t.includes(search))&&(p==="all"||o.payment_status===p)&&(f==="all"||o.status===f)});
    $("#ordersBody").innerHTML=a.length?a.map(o=>'<tr><td><div class="strong">'+esc(o.order_number||o.id)+'</div><div class="muted">'+dt(o.created_at)+'</div></td><td><div class="strong">'+esc(orderCustomer(o))+'</div><div class="muted">'+esc(o.customer_email||"")+'</div></td><td>'+esc(o.shipping_street||"-")+' '+esc(o.shipping_house_number||"")+'<div class="muted">'+esc(o.shipping_postal_code||"")+' '+esc(o.shipping_city||"")+'</div></td><td><span class="'+badge(o.payment_status)+'">'+esc(payStatus(o.payment_status))+'</span><div style="margin-top:4px"><span class="'+badge(o.status)+'">'+esc(fulfillStatus(o.status))+'</span></div></td><td class="money">'+money(o.total)+'</td><td><div class="table-actions"><button class="mini-btn" data-act="odetail" data-id="'+esc(o.id)+'">Details</button><button class="mini-btn primary" data-act="onext" data-id="'+esc(o.id)+'">Volgende status</button></div></td></tr>').join(""):'<tr><td colspan="6"><div class="empty"><strong>Geen orders</strong></div></td></tr>';
  }
  function renderEvents(){
    const search=($("#eventSearch")?.value||"").toLowerCase(),st=$("#eventStatus")?.value||"all";
    const a=S.events.filter(e=>{const t=[e.event_name,e.title,e.name,e.organisation,e.email,e.location,e.edition].filter(Boolean).join(" ").toLowerCase();return(!search||t.includes(search))&&(st==="all"||e.status===st)}).sort((x,y)=>String(x.event_date).localeCompare(String(y.event_date)));
    $("#eventsBody").innerHTML=a.length?a.map(e=>'<tr><td><div class="strong">'+date(e.event_date)+'</div><div class="muted">'+time(e.start_time)+'–'+time(e.end_time)+'</div></td><td><div class="strong">'+esc(e.event_name||e.title||"-")+'</div><div class="muted">'+esc(e.organisation||e.name||"-")+'</div></td><td>'+esc(e.location||"-")+'<div class="muted">'+esc(e.guests||"-")+' gasten</div></td><td><span class="badge badge-blue">'+esc(e.edition||"-")+'</span></td><td class="money">'+money(e.final_price)+'</td><td><div class="table-actions"><button class="mini-btn" data-act="edetail" data-id="'+esc(e.id)+'">Details</button><button class="mini-btn primary" data-act="eedit" data-id="'+esc(e.id)+'">Bewerken</button></div></td></tr>').join(""):'<tr><td colspan="6"><div class="empty"><strong>Geen evenementen</strong></div></td></tr>';
  }
  function renderCalendar(){
    const y=S.cal.getFullYear(),m=S.cal.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1);start.setDate(start.getDate()-((start.getDay()+6)%7));const end=new Date(y,m+1,0);end.setDate(end.getDate()+(6-((end.getDay()+6)%7)));
    $("#calendarTitle").textContent=new Intl.DateTimeFormat("nl-BE",{month:"long",year:"numeric"}).format(first);
    const days=[];for(const d=new Date(start);d<=end;d.setDate(d.getDate()+1))days.push(new Date(d));
    $("#calendarGrid").innerHTML=["Ma","Di","Wo","Do","Vr","Za","Zo"].map(x=>'<div class="cal-week">'+x+"</div>").join("")+days.map(d=>{const iso=d.toISOString().slice(0,10),ev=S.events.filter(x=>x.status==="confirmed"&&x.event_date===iso),today=new Date().toISOString().slice(0,10);return'<div class="cal-day '+(d.getMonth()!==m?"other ":"")+(iso===today?"today":"")+'"><div class="cal-num">'+d.getDate()+"</div>"+ev.slice(0,4).map(e=>'<button class="cal-event" data-act="edetail" data-id="'+esc(e.id)+'">'+esc(e.event_name||e.title||"Event")+"</button>").join("")+(ev.length>4?'<div class="muted" style="font-size:9px;margin-top:4px">+'+(ev.length-4)+" meer</div>":"")+"</div>"}).join("");
  }
  function customerRows(){
    const map=new Map();const add=(name,email,phone,orders,revenue,last)=>{const key=(email||phone||name||"").toLowerCase();const r=map.get(key)||{name:name||"-",email:email||"-",phone:phone||"-",orders:0,revenue:0,last:""};r.orders+=orders||0;r.revenue+=revenue||0;if(String(last)>String(r.last))r.last=last;map.set(key,r)};
    S.orders.forEach(o=>add(orderCustomer(o),o.customer_email,o.customer_phone,1,Number(o.total||0),o.created_at));S.quotes.forEach(q=>add(q.name,q.email,q.phone,0,0,q.created_at));return[...map.values()].sort((a,b)=>b.revenue-a.revenue);
  }
  function renderCustomers(){const a=customerRows();$("#customersBody").innerHTML=a.length?a.map(c=>'<tr><td class="strong">'+esc(c.name)+'</td><td>'+esc(c.email)+'</td><td>'+esc(c.phone)+'</td><td>'+c.orders+"</td><td class=\"money\">"+money(c.revenue)+"</td><td>"+date(c.last)+"</td></tr>").join(""):'<tr><td colspan="6"><div class="empty"><strong>Geen klanten</strong></div></td></tr>'}
  function productTotals(){
    const map=new Map();S.orders.filter(o=>o.payment_status==="paid").forEach(o=>(Array.isArray(o.order_items)?o.order_items:[]).forEach(i=>{const k=i.product_id||i.product_name||"onbekend";const r=map.get(k)||{name:i.product_name||k,units:0,grams:0,revenue:0};r.units+=Number(i.quantity||0);r.grams+=Number(i.meta?.grams||0)*Number(i.quantity||0);r.revenue+=Number(i.line_total??((Number(i.unit_price)||0)*(Number(i.quantity)||0)));map.set(k,r)}));return[...map.values()].sort((a,b)=>b.revenue-a.revenue)
  }
  function renderProducts(){const a=productTotals();$("#productsBody").innerHTML=a.length?a.map(p=>'<tr><td class="strong">'+esc(p.name)+'</td><td>'+p.units+'</td><td>'+p.grams.toLocaleString("nl-BE")+" g</td><td class=\"money\">"+money(p.revenue)+"</td></tr>").join(""):'<tr><td colspan="4"><div class="empty"><strong>Geen verkoopdata</strong></div></td></tr>';$("#inventoryBody").innerHTML=S.availability.inventory&&S.inventory.length?S.inventory.map(x=>'<tr><td class="strong">'+esc(x.name)+'</td><td>'+esc(x.sku||"-")+'</td><td>'+Number(x.stock_quantity||0)+" "+esc(x.unit||"stuks")+'</td><td>'+Number(x.min_stock||0)+'</td><td>'+money(x.cost_per_unit)+'</td><td><button class="mini-btn primary" data-act="inv-edit" data-id="'+esc(x.id)+'">Bewerken</button></td></tr>').join(""):'<tr><td colspan="6"><div class="empty"><strong>Voorraadmodule</strong>'+ (S.availability.inventory?"Nog geen voorraadregels.":"Voer de meegeleverde database-setup uit om voorraad te activeren.")+"</div></td></tr>"}
  function renderFinance(){const m=metrics();$("#financeTotal").textContent=money(m.total);$("#financeWebshop").textContent=money(m.webshop);$("#financeEvents").textContent=money(m.eventRev);$("#financeExpense").textContent=money(S.expenses.reduce((a,e)=>a+Number(e.amount||0),0));$("#financeBody").innerHTML=S.availability.expenses&&S.expenses.length?S.expenses.sort((a,b)=>String(b.expense_date).localeCompare(String(a.expense_date))).map(e=>'<tr><td>'+date(e.expense_date)+'</td><td class="strong">'+esc(e.category||"-")+'</td><td>'+esc(e.description||"-")+'</td><td class="money">'+money(e.amount)+'</td><td><button class="mini-btn danger" data-act="expense-delete" data-id="'+esc(e.id)+'">Verwijder</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty"><strong>Geen kosten geregistreerd</strong>'+(!S.availability.expenses?"Activeer de financiële tabel via de setup-SQL.":"")+"</div></td></tr>"}
  function renderStaff(){if(!S.availability.staff){$("#staffBody").innerHTML='<tr><td colspan="4"><div class="empty"><strong>Medewerkersmodule nog niet geactiveerd</strong>De database-setup maakt persoonlijke accounts en rollen mogelijk.</div></td></tr>';return}$("#staffBody").innerHTML=S.staff.map(s=>'<tr><td><div class="strong">'+esc(s.full_name||"-")+'</div><div class="muted">'+esc(s.email||"")+'</div></td><td><span class="badge badge-blue">'+esc(s.role||"staff")+"</span></td><td><span class=\""+(s.is_active===false?"badge badge-red":"badge badge-green")+'">'+(s.is_active===false?"Inactief":"Actief")+'</span></td><td><button class="mini-btn primary" data-act="staff-toggle" data-id="'+esc(s.id)+'">'+(s.is_active===false?"Activeren":"Deactiveren")+"</button></td></tr>").join("")||'<tr><td colspan="4"><div class="empty"><strong>Geen medewerkers</strong></div></td></tr>'}
  function renderTasks(){if(!S.availability.tasks){$("#tasksBody").innerHTML='<div class="notice"><strong>Taakmodule nog niet actief.</strong>Voer de setup-SQL uit.</div>';return}const a=[...S.tasks].sort((x,y)=>String(x.due_date||"").localeCompare(String(y.due_date||"")));$("#tasksBody").innerHTML=a.length?a.map(t=>'<div class="list-item"><div class="list-main"><strong>'+esc(t.title)+'</strong><span>'+esc(t.description||"")+' · deadline '+date(t.due_date||"")+'</span></div><div><span class="'+badge(t.status)+'">'+esc(t.status||"open")+'</span><button class="mini-btn primary" style="margin-left:6px" data-act="task-next" data-id="'+esc(t.id)+'">Volgende</button></div></div>').join(""):'<div class="empty"><strong>Geen taken</strong></div>'}
  function renderReports(){$("#reportSummary").innerHTML='<div class="grid-3"><div class="kpi"><div class="kpi-label">Aanvragen</div><div class="kpi-value">'+S.quotes.length+"</div></div><div class=\"kpi\"><div class=\"kpi-label\">Orders</div><div class=\"kpi-value\">"+S.orders.length+"</div></div><div class=\"kpi\"><div class=\"kpi-label\">Events</div><div class=\"kpi-value\">"+S.events.filter(e=>e.status==="confirmed").length+"</div></div></div>"}
  function renderSettings(){$("#settingsState").innerHTML='<div class="list"><div class="list-item"><div class="list-main"><strong>Vercel API</strong><span>/api/admin server-side beheer</span></div><span class="badge badge-green">Actief</span></div><div class="list-item"><div class="list-main"><strong>Supabase</strong><span>Service-role via server-side API</span></div><span class="badge badge-green">Actief</span></div><div class="list-item"><div class="list-main"><strong>Mollie</strong><span>Webshopbetaling en webhook</span></div><span class="badge badge-cyan">Actief</span></div><div class="list-item"><div class="list-main"><strong>Voorraad</strong><span>Extra tabel '+(S.availability.inventory?"gevonden":"ontbreekt")+'</span></div><span class="'+(S.availability.inventory?"badge badge-green":"badge badge-amber")+'">'+(S.availability.inventory?"Actief":"Setup vereist")+'</span></div><div class="list-item"><div class="list-main"><strong>Medewerkers</strong><span>Persoonlijke accounts en rollen</span></div><span class="'+(S.availability.staff?"badge badge-green":"badge badge-amber")+'">'+(S.availability.staff?"Actief":"Setup vereist")+"</span></div></div>"}
  function modal(titleText,sub,html,onDone){$("#modalTitle").textContent=titleText;$("#modalSubtitle").textContent=sub||"";$("#modalBody").innerHTML=html;$("#modal").classList.add("open");if(onDone)onDone()}
  function closeModal(){$("#modal").classList.remove("open")}
  function qDetail(q){modal("Aanvraag",q.event_name||"Details",'<div class="grid-2"><div class="notice"><strong>Klant</strong><br>'+esc(q.name||"-")+'<br>'+esc(q.organisation||"-")+'<br>'+esc(q.email||"-")+'<br>'+esc(q.phone||"-")+'</div><div class="notice"><strong>Event</strong><br>'+esc(q.event_name||"-")+'<br>'+date(q.event_date)+' · '+time(q.start_time)+'–'+time(q.end_time)+'<br>'+esc(q.location||"-")+'<br>'+esc(q.guests||"-")+' gasten</div></div><div class="notice" style="margin-top:12px"><strong>Formule</strong><br>'+esc(q.edition||"-")+' · '+money(q.final_price??q.estimated_price)+'<br><br><strong>Notities</strong><br>'+esc(q.practical_notes||q.message||"Geen")+"</div>")}
  function oDetail(o){const items=Array.isArray(o.order_items)?o.order_items:[];modal("Bestelling",o.order_number||o.id||"Order",'<div class="grid-2"><div class="notice"><strong>Klant</strong><br>'+esc(orderCustomer(o))+'<br>'+esc(o.customer_email||"-")+'<br>'+esc(o.customer_phone||"-")+'</div><div class="notice"><strong>Levering</strong><br>'+esc(o.shipping_street||"-")+' '+esc(o.shipping_house_number||"")+'<br>'+esc(o.shipping_postal_code||"")+' '+esc(o.shipping_city||"")+'</div></div><div class="notice" style="margin-top:12px"><strong>Producten</strong><br>'+items.map(i=>esc(i.quantity)+" × "+esc(i.product_name||"Product")+" · "+money(i.line_total??((Number(i.unit_price)||0)*(Number(i.quantity)||0)))+(i.meta?.grams?" · "+esc(i.meta.grams)+" g":"")).join("<br>")+'<br><br><strong>Status</strong><br>'+esc(payStatus(o.payment_status))+' · '+esc(fulfillStatus(o.status))+'<br><br><strong>Totaal</strong> '+money(o.total)+'</div>')}
  function eDetail(e){modal("Evenement",e.event_name||e.title||"Details",'<div class="grid-2"><div class="notice"><strong>Klant</strong><br>'+esc(e.name||"-")+'<br>'+esc(e.organisation||"-")+'<br>'+esc(e.email||"-")+'<br>'+esc(e.phone||"-")+'</div><div class="notice"><strong>Planning</strong><br>'+date(e.event_date)+' · '+time(e.start_time)+'–'+time(e.end_time)+'<br>'+esc(e.location||"-")+'<br>'+esc(e.guests||"-")+' gasten</div></div><div class="notice" style="margin-top:12px"><strong>Formule</strong><br>'+esc(e.edition||"-")+' · '+money(e.final_price)+'<br><br><strong>Praktisch</strong><br>'+esc(e.practical_notes||"Geen")+"</div>")}
  function qForm(q){
    const h='<form id="editForm"><div class="form-grid"><div class="field"><label>Naam</label><input id="f_name" value="'+esc(q?.name||"")+'"></div><div class="field"><label>Organisatie</label><input id="f_org" value="'+esc(q?.organisation||"")+'"></div><div class="field"><label>E-mail</label><input id="f_email" value="'+esc(q?.email||"")+'"></div><div class="field"><label>Telefoon</label><input id="f_phone" value="'+esc(q?.phone||"")+'"></div><div class="field"><label>Eventnaam</label><input id="f_event" value="'+esc(q?.event_name||"")+'"></div><div class="field"><label>Datum</label><input id="f_date" type="date" value="'+esc(q?.event_date||"")+'"></div><div class="field"><label>Start</label><input id="f_start" type="time" value="'+esc(time(q?.start_time)==="-"?"":time(q?.start_time))+'"></div><div class="field"><label>Einde</label><input id="f_end" type="time" value="'+esc(time(q?.end_time)==="-"?"":time(q?.end_time))+'"></div><div class="field"><label>Locatie</label><input id="f_loc" value="'+esc(q?.location||"")+'"></div><div class="field"><label>Gasten</label><input id="f_guests" type="number" min="1" value="'+esc(q?.guests||"")+'"></div><div class="field"><label>Formule</label><select id="f_edition"><option value="waffle">Waffle</option><option value="candy">Candy</option><option value="both">Waffle + Candy</option></select></div><div class="field"><label>Status</label><select id="f_status"><option value="new">Nieuw</option><option value="in_progress">In behandeling</option><option value="accepted">Aanvaard</option><option value="rejected">Geweigerd</option></select></div><div class="field"><label>Geschat</label><input id="f_est" type="number" step="0.01" value="'+esc(q?.estimated_price||"")+'"></div><div class="field"><label>Definitief</label><input id="f_final" type="number" step="0.01" value="'+esc(q?.final_price||"")+'"></div><div class="field full"><label>Notities</label><textarea id="f_notes">'+esc(q?.practical_notes||q?.message||"")+'</textarea></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Opslaan</button></div></form>';
    modal(q?"Aanvraag bewerken":"Nieuwe aanvraag","Gegevens",h,()=>{$("#f_edition").value=q?.edition||"waffle";$("#f_status").value=q?.status||"new";$("#editForm").addEventListener("submit",async ev=>{ev.preventDefault();const p={name:$("#f_name").value.trim(),organisation:$("#f_org").value.trim(),email:$("#f_email").value.trim(),phone:$("#f_phone").value.trim(),event_name:$("#f_event").value.trim(),event_date:$("#f_date").value||null,start_time:$("#f_start").value||null,end_time:$("#f_end").value||null,location:$("#f_loc").value.trim(),guests:$("#f_guests").value?Number($("#f_guests").value):null,edition:$("#f_edition").value,status:$("#f_status").value,estimated_price:$("#f_est").value?Number($("#f_est").value):null,final_price:$("#f_final").value?Number($("#f_final").value):null,practical_notes:$("#f_notes").value};try{await api(q?"updateQuote":"createQuote",{id:q?.id,payload:p});closeModal();await load();toast("Aanvraag opgeslagen.","success")}catch(e){toast(e.message,"error")}})})
  }
  function eForm(e){
    const h='<form id="editForm"><div class="form-grid"><div class="field"><label>Klant</label><input id="f_name" value="'+esc(e?.name||"")+'"></div><div class="field"><label>Organisatie</label><input id="f_org" value="'+esc(e?.organisation||"")+'"></div><div class="field"><label>E-mail</label><input id="f_email" value="'+esc(e?.email||"")+'"></div><div class="field"><label>Telefoon</label><input id="f_phone" value="'+esc(e?.phone||"")+'"></div><div class="field"><label>Evenement</label><input id="f_event" value="'+esc(e?.event_name||e?.title||"")+'"></div><div class="field"><label>Datum</label><input id="f_date" type="date" value="'+esc(e?.event_date||"")+'"></div><div class="field"><label>Start</label><input id="f_start" type="time" value="'+esc(time(e?.start_time)==="-"?"":time(e?.start_time))+'"></div><div class="field"><label>Einde</label><input id="f_end" type="time" value="'+esc(time(e?.end_time)==="-"?"":time(e?.end_time))+'"></div><div class="field"><label>Locatie</label><input id="f_loc" value="'+esc(e?.location||"")+'"></div><div class="field"><label>Gasten</label><input id="f_guests" type="number" value="'+esc(e?.guests||"")+'"></div><div class="field"><label>Formule</label><select id="f_edition"><option value="waffle">Waffle</option><option value="candy">Candy</option><option value="both">Waffle + Candy</option></select></div><div class="field"><label>Prijs</label><input id="f_final" type="number" step="0.01" value="'+esc(e?.final_price||"")+'"></div><div class="field"><label>Status</label><select id="f_status"><option value="confirmed">Bevestigd</option><option value="cancelled">Geannuleerd</option></select></div><div class="field"><label>Type</label><input id="f_type" value="'+esc(e?.event_type||"")+'"></div><div class="field full"><label>Praktische notities</label><textarea id="f_notes">'+esc(e?.practical_notes||"")+'</textarea></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Opslaan</button></div></form>';
    modal(e?"Evenement bewerken":"Nieuw evenement","Planning",h,()=>{$("#f_edition").value=e?.edition||"waffle";$("#f_status").value=e?.status||"confirmed";$("#editForm").addEventListener("submit",async ev=>{ev.preventDefault();const p={name:$("#f_name").value.trim(),organisation:$("#f_org").value.trim(),email:$("#f_email").value.trim(),phone:$("#f_phone").value.trim(),event_name:$("#f_event").value.trim(),title:$("#f_event").value.trim(),event_date:$("#f_date").value||null,start_time:$("#f_start").value||null,end_time:$("#f_end").value||null,location:$("#f_loc").value.trim(),guests:$("#f_guests").value?Number($("#f_guests").value):null,edition:$("#f_edition").value,final_price:$("#f_final").value?Number($("#f_final").value):null,status:$("#f_status").value,event_type:$("#f_type").value.trim(),practical_notes:$("#f_notes").value};try{await api(e?"updateEvent":"createEvent",{id:e?.id,quote_id:e?.quote_id,payload:p});closeModal();await load();toast("Evenement opgeslagen.","success")}catch(err){toast(err.message,"error")}})})
  }
  function staffForm(){modal("Medewerker toevoegen","Persoonlijk account",'<form id="editForm"><div class="form-grid"><div class="field"><label>Naam</label><input id="f_name" required></div><div class="field"><label>E-mail</label><input id="f_email" type="email" required></div><div class="field"><label>Wachtwoord</label><input id="f_pass" type="password" minlength="8" required></div><div class="field"><label>Rol</label><select id="f_role"><option value="staff">Medewerker</option><option value="manager">Manager</option><option value="finance">Financieel</option><option value="warehouse">Magazijn</option></select></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Aanmaken</button></div></form>',()=>$("#editForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("createStaff",{full_name:$("#f_name").value,email:$("#f_email").value,password:$("#f_pass").value,role:$("#f_role").value});closeModal();await load();toast("Medewerker aangemaakt.","success")}catch(err){toast(err.message,"error")}}))}
  function invForm(i){modal(i?"Voorraad bewerken":"Voorraad toevoegen","Voorraad",'<form id="editForm"><div class="form-grid"><div class="field"><label>Productnaam</label><input id="f_name" value="'+esc(i?.name||"")+'" required></div><div class="field"><label>SKU</label><input id="f_sku" value="'+esc(i?.sku||"")+'"></div><div class="field"><label>Eenheid</label><input id="f_unit" value="'+esc(i?.unit||"stuks")+'"></div><div class="field"><label>Voorraad</label><input id="f_stock" type="number" step="0.01" value="'+esc(i?.stock_quantity??0)+'"></div><div class="field"><label>Minimum</label><input id="f_min" type="number" step="0.01" value="'+esc(i?.min_stock??0)+'"></div><div class="field"><label>Kostprijs</label><input id="f_cost" type="number" step="0.01" value="'+esc(i?.cost_per_unit??0)+'"></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Opslaan</button></div></form>',()=>$("#editForm").addEventListener("submit",async e=>{e.preventDefault();const p={name:$("#f_name").value.trim(),sku:$("#f_sku").value.trim(),unit:$("#f_unit").value.trim(),stock_quantity:Number($("#f_stock").value||0),min_stock:Number($("#f_min").value||0),cost_per_unit:Number($("#f_cost").value||0)};try{await api(i?"updateInventory":"createInventory",{id:i?.id,payload:p});closeModal();await load();toast("Voorraad opgeslagen.","success")}catch(err){toast(err.message,"error")}}))}
  function expenseForm(){modal("Kosten toevoegen","Financieel",'<form id="editForm"><div class="form-grid"><div class="field"><label>Datum</label><input id="f_date" type="date" required value="'+new Date().toISOString().slice(0,10)+'"></div><div class="field"><label>Categorie</label><input id="f_cat" placeholder="Inkoop, personeel, transport…"></div><div class="field"><label>Omschrijving</label><input id="f_desc"></div><div class="field"><label>Bedrag</label><input id="f_amount" type="number" step="0.01" required></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Opslaan</button></div></form>',()=>$("#editForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("createExpense",{payload:{expense_date:$("#f_date").value,category:$("#f_cat").value,description:$("#f_desc").value,amount:Number($("#f_amount").value||0)}});closeModal();await load();toast("Kosten opgeslagen.","success")}catch(err){toast(err.message,"error")}}))}
  function taskForm(){modal("Taak toevoegen","Operationeel",'<form id="editForm"><div class="form-grid"><div class="field"><label>Titel</label><input id="f_title" required></div><div class="field"><label>Prioriteit</label><select id="f_priority"><option value="normal">Normaal</option><option value="high">Hoog</option><option value="urgent">Dringend</option></select></div><div class="field"><label>Deadline</label><input id="f_date" type="date"></div><div class="field"><label>Status</label><select id="f_status"><option value="open">Open</option><option value="in_progress">In behandeling</option></select></div><div class="field full"><label>Omschrijving</label><textarea id="f_desc"></textarea></div></div><div class="modal-foot"><button type="button" class="soft-button" data-close>Annuleren</button><button class="primary-button">Opslaan</button></div></form>',()=>$("#editForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("createTask",{payload:{title:$("#f_title").value,priority:$("#f_priority").value,due_date:$("#f_date").value||null,status:$("#f_status").value,description:$("#f_desc").value}});closeModal();await load();toast("Taak aangemaakt.","success")}catch(err){toast(err.message,"error")}}))}
  function exportCsv(name,rows){if(!rows.length){toast("Geen data om te exporteren.","warning");return}const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))],csv="\uFEFF"+[headers,...rows.map(r=>headers.map(h=>'"'+String(typeof r[h]==="object"?JSON.stringify(r[h]):r[h]??"").replace(/"/g,'""')+'"'))].map(a=>a.join(";")).join("\n"),b=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function orderNext(o){const next={new:"preparing",preparing:"ready",ready:"shipped",shipped:"completed"}[o.status]||"completed";api("updateOrder",{id:o.id,payload:{status:next}}).then(()=>{load();toast("Bestelling bijgewerkt.","success")}).catch(e=>toast(e.message,"error"))}
  document.addEventListener("click",e=>{
    const link=e.target.closest("[data-section-link]");if(link){section(link.dataset.sectionLink);return}
    const nav=e.target.closest(".nav-btn");if(nav){section(nav.dataset.section);return}
    if(e.target.closest("#mobileMenu")){$("#sidebar").classList.toggle("open");return}
    if(e.target.closest("#logout")){logout();return}
    if(e.target.closest("#loginButton")){login();return}
    const close=e.target.closest("[data-close]");if(close){closeModal();return}
    if(e.target.id==="modal"){closeModal();return}
    const btn=e.target.closest("[data-act]");if(!btn)return;const id=btn.dataset.id;
    if(btn.dataset.act==="qdetail"){const x=S.quotes.find(a=>String(a.id)===String(id));if(x)qDetail(x)}
    if(btn.dataset.act==="qedit"){const x=S.quotes.find(a=>String(a.id)===String(id));qForm(x)}
    if(btn.dataset.act==="qaccept"){api("acceptQuote",{id}).then(load).then(()=>toast("Aanvraag aanvaard.","success")).catch(async err=>{if(err.message.includes("overlappend")){if(confirm(err.message+" Toch aanvaarden?"))api("acceptQuote",{id,force:true}).then(load).then(()=>toast("Aanvraag aanvaard.","success")).catch(e=>toast(e.message,"error"))}else toast(err.message,"error")})}
    if(btn.dataset.act==="odetail"){const x=S.orders.find(a=>String(a.id)===String(id));if(x)oDetail(x)}
    if(btn.dataset.act==="onext"){const x=S.orders.find(a=>String(a.id)===String(id));if(x)orderNext(x)}
    if(btn.dataset.act==="edetail"){const x=S.events.find(a=>String(a.id)===String(id));if(x)eDetail(x)}
    if(btn.dataset.act==="eedit"){const x=S.events.find(a=>String(a.id)===String(id));eForm(x)}
    if(btn.dataset.act==="inv-edit"){const x=S.inventory.find(a=>String(a.id)===String(id));invForm(x)}
    if(btn.dataset.act==="expense-delete"){api("deleteExpense",{id}).then(load).then(()=>toast("Kosten verwijderd.","success")).catch(err=>toast(err.message,"error"))}
    if(btn.dataset.act==="staff-toggle"){const x=S.staff.find(a=>String(a.id)===String(id));if(x)api("updateStaff",{id,payload:{is_active:x.is_active===false}}).then(load).then(()=>toast("Medewerkerstatus aangepast.","success")).catch(err=>toast(err.message,"error"))}
    if(btn.dataset.act==="task-next"){const x=S.tasks.find(a=>String(a.id)===String(id));if(x){const next={open:"in_progress",in_progress:"completed",completed:"open"}[x.status]||"completed";api("updateTask",{id,payload:{status:next}}).then(load).then(()=>toast("Taakstatus aangepast.","success")).catch(err=>toast(err.message,"error"))}}
    const ex=e.target.closest("[data-export]");if(ex){const t=ex.dataset.export;if(t==="orders")exportCsv("hummiebear-orders.csv",S.orders);if(t==="quotes")exportCsv("hummiebear-aanvragen.csv",S.quotes);if(t==="events")exportCsv("hummiebear-events.csv",S.events);if(t==="customers")exportCsv("hummiebear-klanten.csv",customerRows())}
  });
  ["quoteSearch","quoteStatus","quoteEdition","orderSearch","orderPayment","orderFulfillment","eventSearch","eventStatus"].forEach(id=>document.addEventListener("input",e=>{if(e.target.id===id)render()}));
  $("#calendarPrev")?.addEventListener("click",()=>{S.cal.setMonth(S.cal.getMonth()-1);renderCalendar()});
  $("#calendarNext")?.addEventListener("click",()=>{S.cal.setMonth(S.cal.getMonth()+1);renderCalendar()});
  $("#calendarToday")?.addEventListener("click",()=>{S.cal=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCalendar()});
  $("#refreshButton")?.addEventListener("click",()=>load().then(()=>toast("Dashboard vernieuwd.","success")).catch(e=>toast(e.message,"error")));
  $("#lockButton")?.addEventListener("click",logout);
  $("#newQuote")?.addEventListener("click",()=>qForm(null));
  $("#newEvent")?.addEventListener("click",()=>eForm(null));
  $("#newInventory")?.addEventListener("click",()=>invForm(null));
  $("#newExpense")?.addEventListener("click",()=>expenseForm());
  $("#newTask")?.addEventListener("click",()=>taskForm());
  $("#newStaff")?.addEventListener("click",()=>staffForm());
  $("#exportOrders")?.addEventListener("click",()=>exportCsv("hummiebear-orders.csv",S.orders));
  $("#exportQuotes")?.addEventListener("click",()=>exportCsv("hummiebear-aanvragen.csv",S.quotes));
  $("#exportEvents")?.addEventListener("click",()=>exportCsv("hummiebear-events.csv",S.events));
  $("#loginPin")?.addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("#loginPassword")?.addEventListener("keydown",e=>{if(e.key==="Enter")login()});
  window.HBAdmin={load,section};
  start();
})();