const menuToggle=document.querySelector('.menu-toggle');const mainNav=document.querySelector('.main-nav');if(menuToggle&&mainNav){menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open?'true':'false')});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>{mainNav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}))}
const dateInput=document.querySelector('input[name="date"]');if(dateInput){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());dateInput.min=d.toISOString().split('T')[0]}
const editionInputs=[...document.querySelectorAll('input[name="editions"]')];const waffleFields=document.getElementById('waffle-fields');const candyFields=document.getElementById('candy-fields');
if(candyFields){candyFields.innerHTML='<h4>Gepersonaliseerde snoepzakken</h4><p class="extra-intro">Wil je snoepzakken op maat? Kies hieronder hoe je ze wilt samenstellen. Ideaal voor Chiro, KSA, Scouts, scholen en verenigingen.</p><label class="check-line bag-choice"><input id="personalized-bags" type="checkbox" name="candy_options" value="Gepersonaliseerde snoepzakken"> Ja, ik wil gepersonaliseerde snoepzakken</label><div id="bag-customization" class="bag-customization" hidden><div class="bag-grid"><label>Aantal snoepzakken *<select name="bag_quantity"><option value="">Kies aantal</option><option>25 – 50</option><option>51 – 100</option><option>101 – 150</option><option>150+</option></select></label><label>Hoe wil je de zak samenstellen?<select name="bag_style"><option>Laat Hummie Bear een leuke mix samenstellen</option><option>Ik wil zelf aangeven welke snoepen erin komen</option></select></label></div><label>Welke snoepen wil je erin? <small>Je mag zelf soorten of voorkeuren doorgeven. We bekijken samen wat beschikbaar is.</small><textarea name="bag_sweets" rows="4" placeholder="bv. vooral zure snoepen, colasmaak, geen drop..."></textarea></label><label>Personalisatie / tekst op de snoepzakken <small>bv. Chiro De Speelclub • Zomerfeest 2027</small><input type="text" name="bag_personalization" placeholder="Naam, logo-idee of korte tekst"></label><p class="extra-note"><strong>Prijs:</strong> bij grotere aantallen maken we een voordelige prijs per snoepzak op maat.</p></div>'}
const personalizedBags=document.getElementById('personalized-bags');const bagCustomization=document.getElementById('bag-customization');function updateBagPanel(){if(bagCustomization)bagCustomization.hidden=!personalizedBags?.checked}if(personalizedBags){personalizedBags.addEventListener('change',updateBagPanel);updateBagPanel()}
if(waffleFields){const toppingLabel=[...waffleFields.querySelectorAll('.check-line')].find(label=>label.textContent.toLowerCase().includes('extra toppings'));if(toppingLabel)toppingLabel.remove()}
function updateEditionPanels(){const vals=editionInputs.filter(i=>i.checked).map(i=>i.value);const waffle=vals.includes('Hummie Bear Waffle Edition')||vals.includes('Beide editions');const candy=vals.includes('Hummie Bear Candy Edition')||vals.includes('Beide editions');if(waffleFields)waffleFields.hidden=!waffle;if(candyFields)candyFields.hidden=!candy}
editionInputs.forEach(input=>input.addEventListener('change',()=>{const both=editionInputs.find(i=>i.value==='Beide editions');const candy=editionInputs.find(i=>i.value==='Hummie Bear Candy Edition');const waffle=editionInputs.find(i=>i.value==='Hummie Bear Waffle Edition');if(input.value==='Beide editions'&&input.checked){if(candy)candy.checked=true;if(waffle)waffle.checked=true}if(input.value!=='Beide editions'&&!input.checked&&both)both.checked=false;if(candy?.checked&&waffle?.checked&&both)both.checked=true;updateEditionPanels()}));updateEditionPanels();
function showToast(message){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timeout);showToast.timeout=setTimeout(()=>toast.classList.remove('show'),5000)}
const form=document.getElementById('booking-form');if(form){form.addEventListener('submit',async e=>{e.preventDefault();if(!editionInputs.some(i=>i.checked)){showToast('Kies eerst Candy Edition, Waffle Edition of beide.');document.querySelector('.edition-options')?.scrollIntoView({behavior:'smooth',block:'center'});return}const guestsInput=form.querySelector('input[name="guests"]');const guests=Number(guestsInput?.value||0);if(guests<25){showToast('Hummie Bear komt vanaf ongeveer 25 personen.');guestsInput?.focus();return}const button=form.querySelector('.submit-button');const original=button?.innerHTML;if(button){button.disabled=true;button.innerHTML='Aanvraag versturen…'}try{const response=await fetch('https://formspree.io/f/xnpqeljn',{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Form submission failed');form.reset();updateEditionPanels();updateBagPanel();showToast('Bedankt! Je offerteaanvraag is goed verstuurd.');setTimeout(()=>document.querySelector('#contact')?.scrollIntoView({behavior:'smooth',block:'start'}),300)}catch(error){console.error(error);showToast('Er ging iets mis. Probeer opnieuw of mail hummiebearbusiness@gmail.com.')}finally{if(button){button.disabled=false;button.innerHTML=original}}})}
document.querySelectorAll('.edition-card').forEach(card=>{card.addEventListener('mousemove',e=>{if(innerWidth<900)return;const r=card.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;card.style.transform=`perspective(900px) rotateX(${((y-r.height/2)/(r.height/2))*-1.5}deg) rotateY(${((x-r.width/2)/(r.width/2))*1.5}deg) translateY(-7px)`});card.addEventListener('mouseleave',()=>card.style.transform='')});
document.querySelectorAll('.booking-form input,.booking-form textarea,.booking-form select').forEach(field=>{field.addEventListener('focus',()=>field.closest('label')?.classList.add('field-focused'));field.addEventListener('blur',()=>field.closest('label')?.classList.remove('field-focused'))});
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const id=link.getAttribute('href');if(!id||id==='#')return;const target=document.querySelector(id);if(!target)return;e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}));