(() => {
"use strict";
const CONFIG={pricePer100g:1.70,freeBagFrom:500,currency:"EUR",locale:"nl-BE",storageKey:"hummieBearShopCartV2",email:"hummiebearbusiness@gmail.com",tiktokUrl:"https://www.tiktok.com/@hummiebear"};
const PRODUCTS=[
["spek-lardons","Spek","Mager spek / lardons","spek","🥓","https://www.ranson.be/assets/uploads/site/001_rebranded/Logo/_1200x630_fit_center-center_82_none/RANSON-LOGO-RGB.jpg?v=1735891437","Lardons"],
["bananen","Bananen","Schuimsnoep met bananensmaak","fruit","🍌","https://assets.haribo.com/image/upload/s--ubpSn0by--/ar_2580%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_804/v1/consumer-sites/nl-be/Products/Bananas-240g-4001686423189.png","Haribo"],
["berries","Berries","Fruitgom met frambozensmaak","fruit","🫐","https://assets.haribo.com/image/upload/s--Wf6tOU8b--/ar_2700%3A3639,c_fill,f_auto,q_60/w_715/v1/consumer-sites/en-us/Products/Haribo-US-Berries-5-oz.png","Haribo"],
["carensac","Carensac","Kleine kleurrijke dropstaafjes","drop","🍬","https://fladis.azureedge.net/erp/0b60616b-966e-447f-ae37-4b0ac3806130.JPG","Haribo"],
["frambooshartjes","Frambooshartjes","Gesuikerde hartjes met frambozensmaak","fruit","❤️","https://candymixmatch.com/cdn/shop/files/haribo_framboos_hartjes_1024x1024.webp?v=1778419298","Haribo"],
["fruitkogels","Fruitkogels","Maoam fruitkogels","fruit","🟠","https://www.snuffelstore.be/wp-content/uploads/2022/04/4001686575192-600x600.jpg","Haribo"],
["gloeiwormen","Gloeiwormen","Fruitige zachte wormen","fruit","🪱","https://cdn.webshopapp.com/shops/255156/files/419552857/400x400x2/haribo-gloeiwormen-bestellen-online.jpg","Haribo"],
["goudbeertjes","Goudbeertjes","Klassieke fruitgombeertjes","fruit","🐻","https://assets.haribo.com/image/upload/s--2uTBijQI--/ar_2637%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_814/v1/consumer-sites/nl-be/Products/Goudberen-250g-5996379305912.png","Haribo"],
["grapefruit","Grapefruit","Pompelmoessmaak","fruit","🍊","https://assets.sainsburys-groceries.co.uk/gol/8101539/1/640x640.jpg","Haribo"],
["happy-cola-groot","Happy Cola groot","Grote colaflesjes","fruit","🥤","https://www.snoepaanhuis.be/68-large_default/happy-cola-groot-150-st-tubo-12kg-haribo.jpg","Haribo"],
["happy-cola-klein","Happy Cola klein","Kleine colaflesjes","fruit","🥤","https://www.bbi-kermesse.com/12698-large_default/SACHET-HAPPY-COLA-HARIBO-40-GR.jpg","Haribo"],
["kersen","Kersen","Zachte dubbele kersen","fruit","🍒","https://cdn.webshopapp.com/shops/255156/files/475622250/400x400x2/haribo-bananen-per-kilo-bestellen.jpg","Haribo"],
["krokodillen","Krokodillen","Krokodillen met fruitgom","fruit","🐊","https://www.bol.com/nl/nl/p/haribo-croco-snoep-krokodil-150-stuks/9200000132414418/","Haribo"],
["letters","Letters","Haribo letters","fruit","🔤","https://static.delhaize.be/medias/sys_master/products/h4f/hf1/13815673946142.jpg?buildNumber=a5097186fcc7b2e134116bd7730052e9777de5e5ff015c6123247f5dc516df97&imwidth=320","Haribo"],
["pasta-frutta","Pasta Frutta","Zure fruitige pasta","zuur","🍓","https://www.snoepaanhuis.be/70-large_default/pasta-frutta-18-x-200g-haribo-veggie.jpg","Haribo"],
["perziken","Perziken","Perzikvormig fruitgum","fruit","🍑","https://assets.haribo.com/image/upload/s--TcX6WJCF--/ar_2658%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_819/v1/consumer-sites/nl-be/Products/Happy-Peaches-250g-5996379380803.png","Haribo"],
["pico-balla","Pico Balla","Kleine kleurrijke fruitgom","fruit","🌈","https://fladis.azureedge.net/erp/0b60616b-966e-447f-ae37-4b0ac3806130.JPG","Haribo"],
["reuze-aardbei","Reuze aardbei","Grote aardbei","fruit","🍓","https://cdn.webshopapp.com/shops/282420/files/287871219/64x44x2/amerikaans.jpg","Haribo"],
["rotella-fruit","Rotella fruit","Fruitige rolletjes","fruit","🍥","https://cdn.webshopapp.com/shops/255156/files/419552857/400x400x2/haribo-gloeiwormen-bestellen-online.jpg","Haribo"],
["rotella-zwart-jojo","Rotella zwart jojo","Zachte dropjojo","drop","🖤","https://www.dropgigant.nl/cdn/shop/files/rotella-250gr.jpg?v=1787684849&width=450","Haribo"],
["schuimaardbei-tacada","Schuimaardbei Tacada","Zacht aardbeienschuim","fruit","🍓","https://assets.haribo.com/image/upload/s--TcX6WJCF--/ar_2658%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_819/v1/consumer-sites/nl-be/Products/Happy-Peaches-250g-5996379380803.png","Haribo"],
["smurfen","Smurfen","Fruitige Smurfen","fruit","🔵","https://cdn.webshopapp.com/shops/255156/files/475692626/400x400x2/bestel-jouw-haribo-smurfen-snoep-online.jpg","Haribo"],
["tutters-spenen","Tutters / Spenen","Snoepjes in speenvorm","fruit","🍼","https://snoepbaron.com/wp-content/uploads/2026/09/Werktekening_cirkel_50cm_Snoepbaron.pdf-e1788340554564.png","Haribo"],
["blue-dummies-sour","Blue Dummies Sour","Zure blauwe tutters","zuur","🔵","https://www.alphaprix.com/8675-tetines-bleues-vrac-astra-ref-al901.html","Astra"],
["bubblegum-bottles","Bubblegum Bottles","Bubblegum colaflesjes","fruit","🥤","https://i0.wp.com/www.online-snoep.nl/wp-content/uploads/2022/02/bubblegum-bottle.png?fit=580%2C500&ssl=1","Astra"],
["bubblegum-tutters","Bubblegum Tutters","Bubblegum spenen","fruit","🍼","https://www-static.snoeppotteke.be/wp-content/uploads/2023/09/MG_7135-scaled.jpg","Astra"],
["chery-cola","Chery Cola","Zure cherry-colaflesjes","zuur","🍒","https://www.bol.com/nl/nl/p/astra-sweets-zure-cherry-colaflesjes-snoep-500-gram/9300000098778825/","Astra"],
["cola-tutten-zuur","Cola Tutten Zuur","Zure cola-spenen","zuur","🍼","https://ollebolle.net/shops/ollebolle/thumbs/colatutten-colatutten-red-band.jpg","Astra"],
["cola-klein-zuur","Cola Klein Zuur","Kleine zure colaflesjes","zuur","🥤","https://media.s-bol.com/???","Astra"],
["confetti","Confetti","Kleurrijke snoepconfetti","mix","🎉","https://lekkergoed.be/wp-content/uploads/2020/07/astra-frisia-confetti-lekkergoed-600x600.png","Astra"],
["eieren","Eieren","Snoepeieren","fruit","🥚","https://snoepstore.nl/251-large_default/zure-beren.jpg","Astra"],
["frieten","Frieten","Zure frietjes","zuur","🍟","http://despekke-lendelede.be/cdn/shop/products/AstraSweetsZureFrietjes.jpg?v=1638211165","Astra"],
["gesuikerde-aardbei","Gesuikerde aardbei","Gesuikerde aardbei","fruit","🍓","https://cdn.webshopapp.com/shops/255156/files/493965779/gesuikerde-aardbei-snoep-in-huis-halen.jpg","Astra"],
["hearts","Hearts","Zoete hartjes","fruit","❤️","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["hotlips","Hotlips","Rode lippen","fruit","💋","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["kersen-zuur","Kersen zuur","Zure kersen","zuur","🍒","https://www.mijnsnoepgoed.nl/cdn/shop/files/haribo-zure-kersen-1kg.jpg","Astra"],
["kikkers-astra","Kikkers","Astra kikkers","fruit","🐸","https://cdn.webshopapp.com/shops/255156/files/494876718/kikker-snoep-van-astra-kopen-online.jpg","Astra"],
["manneke-pis-zuur","Manneke Pis zuur","Zure Manneke Pis","zuur","🧍","https://lekkergoed.be/wp-content/uploads/2023/05/manneke-pis-lekkergoed.png","Astra"],
["manneke-pis-olie","Manneke Pis olie","Manneke Pis met olie","fruit","🧍","https://lekkergoed.be/wp-content/uploads/2023/05/manneke-pis-lekkergoed.png","Astra"],
["muizen","Muizen","Zoete muizen","fruit","🐭","https://lekkergoed.be/wp-content/uploads/2020/07/snoep-frisia-zwarte-muizen-lekkergoed.png","Astra"],
["orka","Orka","Orka-vormig snoep","fruit","🐋","https://lekkergoed.be/wp-content/uploads/2020/07/astra-frisia-orka-lekkergoed.png","Astra"],
["poepekens","Poepekens","Poepekens snoep","fruit","🍑","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["unicones","Unicones","Eenhoorn-snoep","fruit","🦄","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["violetten","Violetten","Violetsnoep","fruit","🟣","https://media.s-bol.com/gJ5LJLKx2rBk/550x550.jpg","Astra"],
["watermeloen-tutters","Watermeloen tutters","Watermeloen-spenen","fruit","🍉","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["winegums","Winegums","Fruitige winegums","fruit","🍬","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["zure-appeltjes","Zure appeltjes","Zure appelvormen","zuur","🍏","https://www.wondergifts.be/web/image/product.template/2212/image_512/Zure%20beertjes%20-%20%E2%82%AC8,20-kg%20-%20per%203kg?unique=833ef0f","Astra"],
["zure-beren","Zure beren","Zure beertjes","zuur","🐻","https://cdn.webshopapp.com/shops/255156/files/494875785/heerlijke-zure-beertjes-van-belgische-snoepfabrika.jpg","Astra"],
["zure-gloeiewormen","Zure gloeïwormen","Zure wormen","zuur","🪱","https://odoo.snoepcenterlingier.be/web/image/product.template/2210/image_1024?unique=5af6f44","Astra"],
["zure-ringen","Zure ringen","Zure ringen","zuur","⭕","https://www.desnoepwinkel.be/images/productimages/big/22.jpg","Astra"],
["zwarte-muizen","Zwarte muizen","Zwarte muizen","drop","🐭","https://cdn.webshopapp.com/shops/255156/files/423062565/zwarte-muizen-snoepjes-bestellen-online.jpg","Astra"],
["cuberdons","Cuberdons","Belgische cuberdons","fruit","🔺","https://www.candyandmore.be/producten/cuberdons-geldhof","Geldhof"],
["zure-vliegers","Zure vliegers","Zure vliegers","zuur","✈️","https://files.candyandmore.be/cache/products/images/1200x630/1dd28bf14741602b71edaef7a2bcafd5d26167e7_6ef7770a59bb4be17b99b6537466104dfd7a065a.jpg","Geldhof"],
["spaghetti-aardbei","Spaghetti aardbei","Doorstreept op originele lijst","zuur","🍓","https://www.gosupps.com/media/catalog/product/cache/25/image/1500x/040ec09b1e35df139433887a97daa66f/5/1/51YVc-PRKYL.jpg","King Royal"],
["spaghetti-appel","Spaghetti appel","Doorstreept op originele lijst","zuur","🍏","https://www.espace-bonbon.fr/3103-large_default/spaghettini-pomme-500g.jpg","King Royal"],
["spaghetti-cola","Spaghetti cola","Doorstreept op originele lijst","zuur","🥤","https://www.godtesjuk.no/media/catalog/product/s/p/spaghetti-cola-1kg.jpg","King Royal"],
["matten-aardbei","Matten aardbei","Doorstreept op originele lijst","zuur","🍓","https://www.topbako.sk/uploaded/system_files/temp/screenshot-20230217-190739-com-android-chrome-edit-241342697593381%7C5d42631b617d73287a.jpg","King Royal"],
["matten-cola","Matten cola","Doorstreept op originele lijst","zuur","🥤","https://soyouz2.deindeal.ch/api/img?p=products%2F2026%2F4%2FF3D9031A-3911-4F90-B120-416C6687C8B8%2F21134765_1&st=11&v=1775833705","King Royal"],
["matten-appel","Matten appel","Doorstreept op originele lijst","zuur","🍏","https://www.bol.com/be/nl/p/zure-matten-appelsmaak-groene-zure-mat-verjaardag-traktatie-210-stuks/9300000022526891/","King Royal"],
["creamrolls","Creamrolls","Roomgevulde snoeprolletjes","fruit","🍓","https://cbonbons.ch/cdn/shop/files/Histoire-2025-10-06T180112.735.png?v=1759766483&width=990","Vidal"],
["dracula","Dracula","Draculatanden","fruit","🧛","https://www.shopbelgium.net/3780-large_default/lutti-dracula-teeth-gums-200-gr.jpg","Lutti"],
["dracula-zuur","Dracula zuur","Zure draculatanden","zuur","🧛","http://myamericandream.be/cdn/shop/files/Ontwerpzondertitel_70.png?v=1759506917","Lutti"],
["tropical-fish","Tropical Fish","Tropische visjes","fruit","🐠","https://www.snoepaanhuis.be/631-large_default/tropical-fish-3-kg-lutti.jpg","Lutti"],
["kettingen","Kettingen","Snoepkettingen","fruit","📿","https://www.ah.nl/producten/product/wi451877/look-o-look-snoepkettingen-en-horloges","—"]
].map(([id,name,desc,category,emoji,image,brand])=>({id,name,desc,category,emoji,image,brand}));
let cart=loadCart(),currentFilter="all",searchTerm="";
const DEAL_BOXES = [
  {id:"deal-sweet-500",name:"Sweet Deal 500 g",grams:500,price:7.95,badge:"-€0,55",desc:"500 g vaste Hummie Bear mix. €0,55 goedkoper dan los schepsnoep.",image:"https://assets.haribo.com/image/upload/s--2uTBijQI--/ar_2637%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_814/v1/consumer-sites/nl-be/Products/Goudberen-250g-5996379305912.png"},
  {id:"deal-party-1000",name:"Party Box 1 kg",grams:1000,price:15.90,badge:"-€1,10",desc:"1 kg vaste mix voor feestjes, filmavond of familie.",image:"https://assets.haribo.com/image/upload/s--YyLhJmWw--/ar_2658%3A4000%2Cc_fill%2Cf_auto%2Cq_60/w_817/v1/consumer-sites/nl-be/Products/Tanfastics-250g-5012035924034.png"},
  {id:"deal-mega-1500",name:"Mega Sweet 1,5 kg",grams:1500,price:23.75,badge:"-€1,75",desc:"1,5 kg vaste mix voor echte snoepliefhebbers.",image:"images/candy-display.png"}
];
function addDeal(id){
  const deal=DEAL_BOXES.find(x=>x.id===id); if(!deal)return;
  addCustomMix([{id:deal.id,name:deal.name,grams:deal.grams,image:deal.image}],{type:"deal",dealName:deal.name,priceOverride:deal.price,image:deal.image});
}

const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function eur(v){return new Intl.NumberFormat(CONFIG.locale,{style:"currency",currency:CONFIG.currency,minimumFractionDigits:2}).format(Number(v)||0)}
function getProduct(id){return PRODUCTS.find(p=>p.id===id)||null}
function saveCart(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(cart))}catch(e){}renderCart()}
function loadCart(){try{const d=JSON.parse(localStorage.getItem(CONFIG.storageKey)||"[]");return Array.isArray(d)?d.filter(x=>x&&x.id):[]}catch(e){return[]}}
function cartItemsDetailed(){return cart.map(item=>{if(item.customMix){const grams=item.customMix.reduce((a,b)=>a+Number(b.grams||0),0);const meta=item.meta||{};let name=meta.dealName||(meta.type==="gift-box"?"Gepersonaliseerde snoepdoos":meta.type==="personalized-bag"?"Gepersonaliseerde snoepzak":"Mijn gepersonaliseerde snoepmix");return{id:item.id,name,grams,price:Number(meta.priceOverride ?? ((grams/100)*CONFIG.pricePer100g)),image:(item.customMix?.[0]?.image||meta.image||"images/gummy-candy.png"),quantity:item.quantity||1,meta,customMix:item.customMix}}const p=getProduct(item.id);return p?{...p,quantity:item.quantity||1,grams:Number(item.grams||100),price:(Number(item.grams||100)/100)*CONFIG.pricePer100g}:null}).filter(Boolean)}
function cartSubtotal(){return cartItemsDetailed().reduce((s,i)=>s+i.price*i.quantity,0)}
function openCart(){q("#cartModal")?.classList.add("open");document.body.style.overflow="hidden";renderCart()}
function closeCart(){q("#cartModal")?.classList.remove("open");document.body.style.overflow=""}
function addProduct(id,grams=100){const p=getProduct(id);if(!p)return;cart.push({id,grams:Number(grams),quantity:1});saveCart();toast(p.name+" toegevoegd aan je mandje.");openCart()}
function addCustomMix(customMix,meta={}){const grams=customMix.reduce((a,b)=>a+Number(b.grams||0),0);if(grams<=0){toast("Kies eerst je snoep.");return}cart.push({id:"mix-"+Date.now(),quantity:1,customMix,meta});saveCart();toast("Je gepersonaliseerde item staat in je mandje.");openCart()}
function updateQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.quantity=Math.max(0,(item.quantity||1)+delta);if(item.quantity===0)cart=cart.filter(x=>x.id!==id);saveCart()}
function personalizedDescription(i){if(!i.customMix)return i.grams+" g · €"+CONFIG.pricePer100g.toFixed(2)+" / 100 g";const meta=i.meta||{};const parts=[];if(meta.type==="personalized-bag"){parts.push("<strong>Formaat:</strong> "+meta.size+" g");parts.push("<strong>Snoep:</strong> "+i.customMix.map(x=>x.name+" ("+x.grams+" g)").join(", "));parts.push("<strong>Sticker:</strong> "+(meta.sticker||"Geen"));parts.push("<strong>Verpakking:</strong> "+(meta.bagColor||"Geen"));if(meta.note)parts.push("<strong>Boodschap:</strong> "+escapeHtml(meta.note));}else if(meta.type==="gift-box"){parts.push("<strong>Doos:</strong> "+meta.size+" g");parts.push("<strong>Sticker:</strong> "+(meta.sticker||"Geen"));if(meta.note)parts.push("<strong>Boodschap:</strong> "+escapeHtml(meta.note));}else{parts.push("<strong>Inhoud:</strong> "+i.customMix.map(x=>x.name+" ("+x.grams+" g)").join(", "));}return "<p class=\"cart-details\">"+parts.join("<br>")+"</p>"}
function escapeHtml(value){return String(value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function renderCart(){const list=q("#cartItems"),badge=q("#cartCount");if(!list||!badge)return;const items=cartItemsDetailed();badge.textContent=items.reduce((a,b)=>a+b.quantity,0);if(!items.length){list.innerHTML='<div class="cart-empty">Je winkelmandje is nog leeg.<br><br>Stel jouw eigen snoepzak samen!</div>'}else{list.innerHTML=items.map(i=>{const gift=i.grams>=CONFIG.freeBagFrom?'<p style="color:var(--hb-green);font-weight:900">🎁 Gratis snoepzakje inbegrepen</p>':'';return '<div class="cart-item"><div class="cart-item-img"><img src="'+i.image+'" alt="'+i.name+'"></div><div><h3>'+i.name+'</h3>'+personalizedDescription(i)+gift+'<div class="qty"><button type="button" data-qty="-1" data-id="'+i.id+'">−</button><span>'+i.quantity+'</span><button type="button" data-qty="1" data-id="'+i.id+'">+</button></div></div><strong>'+eur(i.price*i.quantity)+'</strong></div>'}).join("")}q("#cartSubtotal").textContent=eur(cartSubtotal());q("#cartTotal").textContent=eur(cartSubtotal())}
function checkout(){const items=cartItemsDetailed();if(!items.length){toast("Je mandje is leeg.");return}const lines=items.map(i=>{if(!i.customMix)return i.quantity+"x "+i.name+" — "+i.grams+" g";const m=i.meta||{};let detail=i.customMix.map(x=>x.name+" "+x.grams+" g").join(", ");if(m.type==="personalized-bag")detail="Formaat "+m.size+" g | Snoep: "+detail+" | Sticker: "+(m.sticker||"Geen")+" | Verpakking: "+(m.bagColor||"Geen")+(m.note?" | Boodschap: "+m.note:"");else if(m.type==="gift-box")detail="Doos "+m.size+" g | Sticker: "+(m.sticker||"Geen")+(m.note?" | Boodschap: "+m.note:"");return i.quantity+"x "+i.name+" — "+detail}).join("\n");const subject=encodeURIComponent("Nieuwe Hummie Bear webshopbestelling");const body=encodeURIComponent("Hallo Hummie Bear,\n\nIk wil graag bestellen:\n"+lines+"\n\nTotaal: "+eur(cartSubtotal())+"\n\nNaam:\nAdres:\nTelefoon:\nE-mail:\n");window.location.href="mailto:"+CONFIG.email+"?subject="+subject+"&body="+body}
function toast(m){const el=q("#toast");if(!el)return;el.textContent=m;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),3000)}
function productCard(p){const crossed=["spaghetti-aardbei","spaghetti-appel","spaghetti-cola","matten-aardbei","matten-cola","matten-appel"].includes(p.id);return '<article class="product-card"><div class="product-visual"><img src="'+p.image+'" alt="'+p.name+'" loading="lazy" onerror="this.onerror=null;this.src=\'images/gummy-candy.png\'"><span class="product-badge">'+(crossed?"OOK OP ORIGINELE LIJST DOORGESTREEPT":p.category==="zuur"?"ZOET-ZUUR":"SCHEPSNOEP")+'</span><span class="product-emoji">'+p.emoji+'</span></div><div class="product-info"><h3>'+p.name+'</h3><p>'+p.desc+'. Zelf te kiezen vanaf 100 g.</p><small style="display:block;color:var(--hb-muted);font-weight:800;margin-top:5px">Merk: '+p.brand+'</small><div class="product-meta"><span class="price">'+eur(CONFIG.pricePer100g)+' <small>/ 100 g</small></span><span style="font-size:9px;color:var(--hb-green);font-weight:900">500 g = zakje cadeau</span></div><div class="product-actions"><button class="btn btn-primary btn-block" type="button" data-add="'+p.id+'">+ Voeg 100 g toe</button><button class="icon-btn" type="button" data-scroll-builder title="Zelf samenstellen">⚙</button></div></div></article>'}
function renderProducts(){const g=q("#productGrid");if(!g)return;const list=PRODUCTS.filter(p=>(currentFilter==="all"||p.category===currentFilter)&&(p.name+" "+p.desc).toLowerCase().includes(searchTerm.toLowerCase()));g.innerHTML=list.length?list.map(productCard).join(""):'<div style="grid-column:1/-1;padding:40px;text-align:center;color:var(--hb-muted)">Geen snoep gevonden.</div>';if(q("#productCount"))q("#productCount").textContent=list.length+" soorten"}
function initShop(){if(!q("#productGrid"))return;renderProducts();qa("[data-filter]").forEach(b=>b.addEventListener("click",()=>{qa("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;renderProducts()}));q("#productSearch")?.addEventListener("input",e=>{searchTerm=e.target.value;renderProducts()});q("#productGrid").addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a)addProduct(a.dataset.add,100);if(e.target.closest("[data-scroll-builder]"))q("#pickMixBuilder")?.scrollIntoView({behavior:"smooth"})})}
function initPickMix(){const wrap=q("#pickMixBuilder");if(!wrap)return;const grid=q(".pick-grid",wrap);if(grid)grid.innerHTML=PRODUCTS.map(p=>'<div class="pick-item"><div class="pick-item-top"><div class="pick-item-photo"><img src="'+p.image+'" alt="'+p.name+'" loading="lazy" onerror="this.onerror=null;this.src=\'images/gummy-candy.png\'"></div><div><strong>'+p.name+'</strong><span>'+eur(CONFIG.pricePer100g)+' / 100 g</span></div></div><div class="pick-step"><button type="button" data-mix-minus="'+p.id+'">−</button><b>0 g</b><button type="button" data-mix-plus="'+p.id+'">+</button></div></div>').join("");const weights=Object.fromEntries(PRODUCTS.map(p=>[p.id,0]));function update(){const parts=Object.entries(weights).filter(([,g])=>g>0).map(([id,grams])=>({id,name:getProduct(id).name,grams})),grams=parts.reduce((a,b)=>a+b.grams,0),price=(grams/100)*CONFIG.pricePer100g;q("#mixWeight").textContent=grams+" g";q("#mixPrice").textContent=eur(price);q("#mixGift").textContent=grams>=CONFIG.freeBagFrom?"🎁 Gratis snoepzakje inbegrepen":grams?("Nog "+(CONFIG.freeBagFrom-grams)+" g tot je gratis snoepzakje."):"";q("#mixSummary").textContent=parts.length?parts.map(x=>x.name+" "+x.grams+" g").join(" · "):"Kies minstens 100 g snoep.";const btn=q("#mixAdd");if(btn)btn.disabled=grams===0;qa(".pick-item",wrap).forEach(card=>{const btn=q("[data-mix-plus]",card),id=btn?.dataset.mixPlus,display=q(".pick-step b",card);if(id&&display)display.textContent=(weights[id]||0)+" g"})}qa("[data-mix-plus]",wrap).forEach(btn=>btn.addEventListener("click",()=>{weights[btn.dataset.mixPlus]+=100;update()}));qa("[data-mix-minus]",wrap).forEach(btn=>btn.addEventListener("click",()=>{weights[btn.dataset.mixMinus]=Math.max(0,weights[btn.dataset.mixMinus]-100);update()}));q("#mixAdd")?.addEventListener("click",()=>addCustomMix(Object.entries(weights).filter(([,g])=>g>0).map(([id,grams])=>({id,name:getProduct(id).name,grams,image:getProduct(id).image})),{type:"pickmix"}));update()}
function initBagBuilder(){const form=q("#bagBuilderForm");if(!form)return;const state={size:500,sticker:"Sweetness on Wheels",note:"",bagColor:"Transparant"};qa("select[data-bag-candy]",form).forEach(sel=>{sel.innerHTML='<option value="" selected disabled>Maak een keuze</option>'+PRODUCTS.map(p=>"<option value=\""+p.id+"\">"+p.name+" — "+p.brand+"</option>").join("")});qa("[data-bag-option]").forEach(el=>el.addEventListener("click",()=>{qa('[data-bag-option="'+el.dataset.bagOption+'"]').forEach(x=>x.classList.remove("active"));el.classList.add("active");state[el.dataset.bagOption]=el.dataset.bagOption==="size"?Number(el.dataset.value):el.dataset.value;update()}));qa("[data-bag-row] select,[data-bag-row] input").forEach(el=>{el.addEventListener("input",update);el.addEventListener("change",update)});form.querySelectorAll("[data-bag-note]").forEach(el=>el.addEventListener("input",()=>state.note=el.value||""));function update(){const rows=qa("[data-bag-row]").map(row=>({id:q("select",row).value,name:getProduct(q("select",row).value)?.name||"",grams:Number(q("[data-bag-grams]",row).value)||0})).filter(x=>x.grams>0),grams=rows.reduce((a,b)=>a+b.grams,0),max=state.size,price=(max/100)*CONFIG.pricePer100g,invalid=qa("[data-bag-row]",form).some(row=>{const g=Number(q("[data-bag-grams]",row).value)||0;return g>0&&!q("select",row).value});q("#bagPrice").textContent=eur(price);q("#bagPriceBottom")&&(q("#bagPriceBottom").textContent=eur(price));q("#bagWeight").textContent=grams+" / "+max+" g ingevuld";q("#bagRemaining").textContent=grams===max?"Perfect gevuld!":grams<max?Math.max(0,max-grams)+" g over":"Je hebt "+(grams-max)+" g te veel.";q("#bagGift").textContent=grams>=CONFIG.freeBagFrom?"🎁 Extra snoepzakje inbegrepen":"";q("#bagAdd").disabled=grams!==max||invalid}q("#bagAdd")?.addEventListener("click",()=>{const rows=qa("[data-bag-row]").map(row=>({id:q("select",row).value,name:getProduct(q("select",row).value)?.name||"",grams:Number(q("[data-bag-grams]",row).value)||0})).filter(x=>x.grams>0),grams=rows.reduce((a,b)=>a+b.grams,0);if(rows.some(x=>!x.id)){toast("Kies een snoepsoort voor elke ingevulde regel.");return}if(grams!==state.size){toast("Vul de zak exact tot "+state.size+" g.");return}addCustomMix(rows,{type:"personalized-bag",size:state.size,sticker:state.sticker,note:state.note,bagColor:state.bagColor})});update()}
function initGiftBoxes(){const form=q("#giftBoxForm");if(!form)return;let size=500,sticker="Voor jou",note="";qa("[data-box-size]").forEach(b=>b.addEventListener("click",()=>{qa("[data-box-size]").forEach(x=>x.classList.remove("active"));b.classList.add("active");size=Number(b.dataset.boxSize);update()}));qa("[data-box-sticker]").forEach(b=>b.addEventListener("click",()=>{qa("[data-box-sticker]").forEach(x=>x.classList.remove("active"));b.classList.add("active");sticker=b.dataset.boxSticker}));q("#boxNote")?.addEventListener("input",e=>note=e.target.value);function update(){q("#boxPrice").textContent=eur(3.5+(size/100)*CONFIG.pricePer100g);q("#boxSize").textContent=size+" g"}q("#boxAdd")?.addEventListener("click",()=>addCustomMix([{name:"Gepersonaliseerde snoepdoos",id:"gift-box",grams:size}],{type:"gift-box",size,sticker,note,priceOverride:3.5+(size/100)*CONFIG.pricePer100g}));update()}
function initPopup(){const p=q("#firstOrderPopup");if(!p)return;let seen=false;try{seen=sessionStorage.getItem("hbFirstPopupSeen")==="1"}catch(e){}if(!seen)setTimeout(()=>p.classList.add("open"),1200);q("#popupClose")?.addEventListener("click",()=>{p.classList.remove("open");try{sessionStorage.setItem("hbFirstPopupSeen","1")}catch(e){}});q("#popupForm")?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());if(!d.consent){toast("Vink de marketingtoestemming aan.");return}try{localStorage.setItem("hbLead",JSON.stringify(d))}catch(err){}p.classList.remove("open");toast("Welkom! Code SWEET10 geeft 10% korting.");try{sessionStorage.setItem("hbFirstPopupSeen","1")}catch(err){}})}
document.addEventListener("click",e=>{const deal=e.target.closest("[data-deal]");if(deal)addDeal(deal.dataset.deal);if(e.target.closest("[data-open-cart]"))openCart();if(e.target.closest("#cartClose"))closeCart();const qty=e.target.closest("[data-qty]");if(qty)updateQty(qty.dataset.id,Number(qty.dataset.qty));if(e.target.closest("#checkoutButton"))checkout()});
q("#cartModal")?.addEventListener("click",e=>{if(e.target===e.currentTarget)closeCart()});
document.addEventListener("DOMContentLoaded",()=>{initShop();initPickMix();initBagBuilder();initGiftBoxes();initPopup();renderCart();q("#tiktokLiveButton")?.addEventListener("click",()=>window.open(CONFIG.tiktokUrl,"_blank","noopener"));});
})();