(() => {
"use strict";
const CONFIG={pricePer100g:1.70,freeBagFrom:500,currency:"EUR",locale:"nl-BE",storageKey:"hummieBearShopCartV2",email:"hummiebearbusiness@gmail.com",tiktokUrl:"https://www.tiktok.com/@hummiebear"};
const PRODUCTS=[
["goudberen","Goudberen","Fruitgum","fruit","🐻","images/gummy-candy.png"],
["happy-cola","Happy Cola flesjes","Colasmaak","fruit","🥤","images/gummy-candy.png"],
["happy-cherries","Happy Cherries","Kers","fruit","🍒","images/candy-display.png"],
["happy-peaches","Happy Peaches","Perzik","fruit","🍑","images/gummy-candy.png"],
["kikkers","Kikkers","Fruitgum","fruit","🐸","images/gummy-candy.png"],
["banaantjes","Banaantjes","Banaan","fruit","🍌","images/gummy-candy.png"],
["zure-wormen","Zure wormen","Zuur","zuur","🪱","images/gummy-candy.png"],
["zure-aardbeien","Zure aardbeien","Zuur fruit","zuur","🍓","images/candy-display.png"],
["aardbei-schijfjes","Aardbei schijfjes","Fruit","fruit","🍓","images/candy-display.png"],
["zure-matten","Zure matten aardbei","Zuur","zuur","🍬","images/gummy-candy.png"],
["zure-tongen","Zure tongen","Zuur","zuur","👅","images/gummy-candy.png"],
["zure-cola","Zure cola flesjes","Zuur / cola","zuur","🥤","images/gummy-candy.png"],
["rode-lippen","Rode lippen","Zacht snoep","fruit","💋","images/gummy-candy.png"],
["smurfen","Smurfen","Fruitgum","fruit","🔵","images/candy-display.png"],
["tangfastics","Tangfastics","Zuur & fruit","zuur","🍭","images/gummy-candy.png"],
["balla-balla","Balla Balla aardbei","Aardbei","fruit","🍓","images/candy-display.png"],
["watermeloen","Watermeloen schijfjes","Watermeloen","fruit","🍉","images/candy-display.png"],
["jelly-beans","Jelly Beans","Bonte mix","mix","🌈","images/candy-display.png"],
["engelse-drop","Engelse drop","Drop","drop","🖤","images/gummy-candy.png"],
["harlekijntjes","Harlekijntjes","Drop / zoet","drop","🍬","images/gummy-candy.png"]
].map(([id,name,desc,category,emoji,image])=>({id,name,desc,category,emoji,image}));
let cart=loadCart(),currentFilter="all",searchTerm="";
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function eur(v){return new Intl.NumberFormat(CONFIG.locale,{style:"currency",currency:CONFIG.currency,minimumFractionDigits:2}).format(Number(v)||0)}
function getProduct(id){return PRODUCTS.find(p=>p.id===id)||null}
function saveCart(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(cart))}catch(e){}renderCart()}
function loadCart(){try{const d=JSON.parse(localStorage.getItem(CONFIG.storageKey)||"[]");return Array.isArray(d)?d.filter(x=>x&&x.id):[]}catch(e){return[]}}
function cartItemsDetailed(){return cart.map(item=>{if(item.customMix){const grams=item.customMix.reduce((a,b)=>a+Number(b.grams||0),0);return{id:item.id,name:"Mijn gepersonaliseerde snoepzak",grams,price:(grams/100)*CONFIG.pricePer100g,image:"images/gummy-candy.png",quantity:item.quantity||1,meta:item.meta||{},customMix:item.customMix}}const p=getProduct(item.id);return p?{...p,quantity:item.quantity||1,grams:Number(item.grams||100),price:(Number(item.grams||100)/100)*CONFIG.pricePer100g}:null}).filter(Boolean)}
function cartSubtotal(){return cartItemsDetailed().reduce((s,i)=>s+i.price*i.quantity,0)}
function openCart(){q("#cartModal")?.classList.add("open");document.body.style.overflow="hidden";renderCart()}
function closeCart(){q("#cartModal")?.classList.remove("open");document.body.style.overflow=""}
function addProduct(id,grams=100){const p=getProduct(id);if(!p)return;cart.push({id,grams:Number(grams),quantity:1});saveCart();toast(p.name+" toegevoegd aan je mandje.");openCart()}
function addCustomMix(customMix,meta={}){const grams=customMix.reduce((a,b)=>a+Number(b.grams||0),0);if(grams<=0){toast("Kies eerst je snoep.");return}cart.push({id:"mix-"+Date.now(),quantity:1,customMix,meta});saveCart();toast("Je gepersonaliseerde item staat in je mandje.");openCart()}
function updateQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.quantity=Math.max(0,(item.quantity||1)+delta);if(item.quantity===0)cart=cart.filter(x=>x.id!==id);saveCart()}
function renderCart(){const list=q("#cartItems"),badge=q("#cartCount");if(!list||!badge)return;const items=cartItemsDetailed();badge.textContent=items.reduce((a,b)=>a+b.quantity,0);if(!items.length){list.innerHTML='<div class="cart-empty">Je winkelmandje is nog leeg.<br><br>Stel jouw eigen snoepzak samen!</div>'}else{list.innerHTML=items.map(i=>{const gift=i.grams>=CONFIG.freeBagFrom?'<p style="color:var(--hb-green);font-weight:900">🎁 Gratis snoepzakje inbegrepen</p>':'';const extra=i.customMix?'<p>'+i.customMix.map(x=>x.name+" "+x.grams+" g").join(" · ")+"</p>":'<p>'+i.grams+" g · €"+CONFIG.pricePer100g.toFixed(2)+" / 100 g</p>";return '<div class="cart-item"><div class="cart-item-img"><img src="'+i.image+'" alt="'+i.name+'"></div><div><h3>'+i.name+'</h3>'+extra+gift+'<div class="qty"><button type="button" data-qty="-1" data-id="'+i.id+'">−</button><span>'+i.quantity+'</span><button type="button" data-qty="1" data-id="'+i.id+'">+</button></div></div><strong>'+eur(i.price*i.quantity)+'</strong></div>'}).join("")}q("#cartSubtotal").textContent=eur(cartSubtotal());q("#cartTotal").textContent=eur(cartSubtotal())}
function checkout(){const items=cartItemsDetailed();if(!items.length){toast("Je mandje is leeg.");return}const lines=items.map(i=>i.customMix?i.quantity+"x "+i.name+" ("+i.customMix.map(x=>x.name+" "+x.grams+"g").join(", ")+")":i.quantity+"x "+i.name+" — "+i.grams+"g").join("\n");const subject=encodeURIComponent("Nieuwe Hummie Bear webshopbestelling");const body=encodeURIComponent("Hallo Hummie Bear,\n\nIk wil graag bestellen:\n"+lines+"\n\nTotaal: "+eur(cartSubtotal())+"\n\nNaam:\nAdres:\nTelefoon:\nE-mail:\n");window.location.href="mailto:"+CONFIG.email+"?subject="+subject+"&body="+body}
function toast(m){const el=q("#toast");if(!el)return;el.textContent=m;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),3000)}
function productCard(p){return '<article class="product-card"><div class="product-visual"><img src="'+p.image+'" alt="'+p.name+'" loading="lazy"><span class="product-badge">'+(p.category==="zuur"?"ZOET-ZUUR":"SCHEPSNOEP")+'</span><span class="product-emoji">'+p.emoji+'</span></div><div class="product-info"><h3>'+p.name+'</h3><p>'+p.desc+'. Zelf te kiezen vanaf 100 g.</p><div class="product-meta"><span class="price">'+eur(CONFIG.pricePer100g)+' <small>/ 100 g</small></span><span style="font-size:9px;color:var(--hb-green);font-weight:900">500 g = zakje cadeau</span></div><div class="product-actions"><button class="btn btn-primary btn-block" type="button" data-add="'+p.id+'">+ Voeg 100 g toe</button><button class="icon-btn" type="button" data-scroll-builder title="Zelf samenstellen">⚙</button></div></div></article>'}
function renderProducts(){const g=q("#productGrid");if(!g)return;const list=PRODUCTS.filter(p=>(currentFilter==="all"||p.category===currentFilter)&&(p.name+" "+p.desc).toLowerCase().includes(searchTerm.toLowerCase()));g.innerHTML=list.length?list.map(productCard).join(""):'<div style="grid-column:1/-1;padding:40px;text-align:center;color:var(--hb-muted)">Geen snoep gevonden.</div>';if(q("#productCount"))q("#productCount").textContent=list.length+" soorten"}
function initShop(){if(!q("#productGrid"))return;renderProducts();qa("[data-filter]").forEach(b=>b.addEventListener("click",()=>{qa("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;renderProducts()}));q("#productSearch")?.addEventListener("input",e=>{searchTerm=e.target.value;renderProducts()});q("#productGrid").addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a)addProduct(a.dataset.add,100);if(e.target.closest("[data-scroll-builder]"))q("#pickMixBuilder")?.scrollIntoView({behavior:"smooth"})})}
function initPickMix(){const wrap=q("#pickMixBuilder");if(!wrap)return;const weights=Object.fromEntries(PRODUCTS.slice(0,8).map(p=>[p.id,0]));function update(){const parts=Object.entries(weights).filter(([,g])=>g>0).map(([id,grams])=>({id,name:getProduct(id).name,grams})),grams=parts.reduce((a,b)=>a+b.grams,0),price=(grams/100)*CONFIG.pricePer100g;q("#mixWeight").textContent=grams+" g";q("#mixPrice").textContent=eur(price);q("#mixGift").textContent=grams>=CONFIG.freeBagFrom?"🎁 Gratis snoepzakje inbegrepen":grams?("Nog "+(CONFIG.freeBagFrom-grams)+" g tot je gratis snoepzakje."):"";q("#mixSummary").textContent=parts.length?parts.map(x=>x.name+" "+x.grams+" g").join(" · "):"Kies minstens 100 g snoep.";const btn=q("#mixAdd");if(btn)btn.disabled=grams===0;qa(".pick-item").forEach(card=>{const id=q("[data-mix-plus]",card)?.dataset.mixPlus;const b=q("[data-mix-plus]",card);const display=q(".pick-step b",card);if(id&&display)display.textContent=(weights[id]||0)+" g"})}qa("[data-mix-plus]").forEach(b=>b.addEventListener("click",()=>{weights[b.dataset.mixPlus]+=100;update()}));qa("[data-mix-minus]").forEach(b=>b.addEventListener("click",()=>{weights[b.dataset.mixMinus]=Math.max(0,weights[b.dataset.mixMinus]-100);update()}));q("#mixAdd")?.addEventListener("click",()=>addCustomMix(Object.entries(weights).filter(([,g])=>g>0).map(([id,grams])=>({id,name:getProduct(id).name,grams})),{type:"pickmix"}));update()}
function initBagBuilder(){const form=q("#bagBuilderForm");if(!form)return;const state={size:500,sticker:"Sweetness on Wheels",note:"",bagColor:"Transparant"};qa("[data-bag-option]").forEach(el=>el.addEventListener("click",()=>{qa('[data-bag-option="'+el.dataset.bagOption+'"]').forEach(x=>x.classList.remove("active"));el.classList.add("active");state[el.dataset.bagOption]=el.dataset.value;update()}));qa("[data-bag-row] select,[data-bag-row] input").forEach(el=>el.addEventListener("input",update));form.querySelectorAll("[data-bag-note]").forEach(el=>el.addEventListener("input",()=>state.note=el.value||""));function update(){const rows=qa("[data-bag-row]").map(row=>({id:q("select",row).value,name:getProduct(q("select",row).value)?.name||"",grams:Number(q("[data-bag-grams]",row).value)||0})).filter(x=>x.grams>0),grams=rows.reduce((a,b)=>a+b.grams,0),max=state.size,price=(max/100)*CONFIG.pricePer100g;q("#bagPrice").textContent=eur(price);q("#bagPriceBottom")&&(q("#bagPriceBottom").textContent=eur(price));q("#bagWeight").textContent=grams+" / "+max+" g ingevuld";q("#bagRemaining").textContent=grams===max?"Perfect gevuld!":grams<max?Math.max(0,max-grams)+" g over":"Je hebt "+(grams-max)+" g te veel.";q("#bagGift").textContent=grams>=CONFIG.freeBagFrom?"🎁 Extra snoepzakje inbegrepen":"";q("#bagAdd").disabled=grams!==max}q("#bagAdd")?.addEventListener("click",()=>{const rows=qa("[data-bag-row]").map(row=>({id:q("select",row).value,name:getProduct(q("select",row).value)?.name||"",grams:Number(q("[data-bag-grams]",row).value)||0})).filter(x=>x.grams>0),grams=rows.reduce((a,b)=>a+b.grams,0);if(grams!==state.size){toast("Vul de zak exact tot "+state.size+" g.");return}addCustomMix(rows,{type:"personalized-bag",size:state.size,sticker:state.sticker,note:state.note,bagColor:state.bagColor})});update()}
function initGiftBoxes(){const form=q("#giftBoxForm");if(!form)return;let size=500,sticker="Voor jou",note="";qa("[data-box-size]").forEach(b=>b.addEventListener("click",()=>{qa("[data-box-size]").forEach(x=>x.classList.remove("active"));b.classList.add("active");size=Number(b.dataset.boxSize);update()}));qa("[data-box-sticker]").forEach(b=>b.addEventListener("click",()=>{qa("[data-box-sticker]").forEach(x=>x.classList.remove("active"));b.classList.add("active");sticker=b.dataset.boxSticker}));q("#boxNote")?.addEventListener("input",e=>note=e.target.value);function update(){q("#boxPrice").textContent=eur(3.5+(size/100)*CONFIG.pricePer100g);q("#boxSize").textContent=size+" g"}q("#boxAdd")?.addEventListener("click",()=>addCustomMix([{name:"Gepersonaliseerde snoepdoos",id:"gift-box",grams:size}],{type:"gift-box",size,sticker,note,boxPrice:3.5+(size/100)*CONFIG.pricePer100g}));update()}
function initPopup(){const p=q("#firstOrderPopup");if(!p)return;let seen=false;try{seen=sessionStorage.getItem("hbFirstPopupSeen")==="1"}catch(e){}if(!seen)setTimeout(()=>p.classList.add("open"),1200);q("#popupClose")?.addEventListener("click",()=>{p.classList.remove("open");try{sessionStorage.setItem("hbFirstPopupSeen","1")}catch(e){}});q("#popupForm")?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());if(!d.consent){toast("Vink de marketingtoestemming aan.");return}try{localStorage.setItem("hbLead",JSON.stringify(d))}catch(err){}p.classList.remove("open");toast("Welkom! Code SWEET10 geeft 10% korting.");try{sessionStorage.setItem("hbFirstPopupSeen","1")}catch(err){}})}
document.addEventListener("click",e=>{if(e.target.closest("[data-open-cart]"))openCart();if(e.target.closest("#cartClose"))closeCart();const qty=e.target.closest("[data-qty]");if(qty)updateQty(qty.dataset.id,Number(qty.dataset.qty));if(e.target.closest("#checkoutButton"))checkout()});
q("#cartModal")?.addEventListener("click",e=>{if(e.target===e.currentTarget)closeCart()});
document.addEventListener("DOMContentLoaded",()=>{initShop();initPickMix();initBagBuilder();initGiftBoxes();initPopup();renderCart();q("#tiktokLiveButton")?.addEventListener("click",()=>window.open(CONFIG.tiktokUrl,"_blank","noopener"));});
})();